/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classes.Pagina;
import classes.Processo;
import classes.Quadro;
import java.util.ArrayList;

import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author leope
 */
public class Tabela extends javax.swing.JFrame {

    public List<Quadro> quadros;
    public Processo processo;
    public List<Quadro> atualQuadrs;

    public Simulador invocador;

    public Tabela(Processo processo, List<Quadro> quadros, Simulador invocador) {
        initComponents();
        this.quadros = quadros;
        this.processo = processo;
        this.invocador = invocador;
        this.atualQuadrs = new ArrayList<Quadro>();

        alimentarTextTab();

    }

    public void alimentarTextTab() {
        List<Pagina> paginas = processo.getPaginas();
        try {
        for (Pagina pagina : paginas) {
            for (Quadro quadro : quadros) {
                if (quadro.getPagina() != null) {
                    if (quadro.getPagina().equals(pagina)) {
                        atualQuadrs.add(quadro);
                    }
                }
            }
        }

        textTab(atualQuadrs);
        atualQuadrs = null;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "A tabela do processo: " + this.processo.getId() + " não pode ser listada!");
        }
    }

    public void textTab(List<Quadro> quadrs) {
        for (Quadro quadr : quadrs) {
            this.tabelaProcesso.append("Endereco do Quadro: \n" + quadr.getId() +"\nEndereco da Pagina\n"+ quadr.getPagina().getId() + "\n");
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProcesso = new javax.swing.JTextArea();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        tabelaProcesso.setColumns(20);
        tabelaProcesso.setForeground(new java.awt.Color(0, 153, 153));
        tabelaProcesso.setRows(5);
        jScrollPane1.setViewportView(tabelaProcesso);

        voltarButton.setBackground(new java.awt.Color(255, 255, 255));
        voltarButton.setForeground(new java.awt.Color(0, 153, 153));
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(voltarButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        invocador.fecharFilha();
    }//GEN-LAST:event_voltarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tabelaProcesso;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
